config/routes.rb
Rails.application.routes.draw do
  get 'users/index'

  get 'pages/home'

  devise_for :users
  mount Ckeditor::Engine => '/ckeditor'
  root 'pages#home'

  resources :users
  resources :posts
  resources :categories

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  validates :title, presence: true
  validates :desc, length: { maximum: 250 }
  default_scope -> { order(created_at: :desc) }

  has_ancestry

  has_many :relationships, dependent: :destroy
  has_many :posts, through: :relationships
end

app/models/ckeditor/asset.rb
class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase

  delegate :url, :current_path, :content_type, to: :data

  validates :data, presence: true
end

app/models/ckeditor/attachment_file.rb
class Ckeditor::AttachmentFile < Ckeditor::Asset
  mount_uploader :data, CkeditorAttachmentFileUploader, mount_on: :data_file_name

  def url_thumb
    @url_thumb ||= Ckeditor::Utils.filethumb(filename)
  end
end

app/models/ckeditor/picture.rb
class Ckeditor::Picture < Ckeditor::Asset
  mount_uploader :data, CkeditorPictureUploader, mount_on: :data_file_name

  def url_content
    url(:content)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  default_scope -> { order(created_at: :desc) }
  mount_uploader :thumbnail, ThumbnailUploader
  validates :title, presence: true
  validates :desc, length: { maximum: 250 }

  belongs_to :user

  has_many :relationships, dependent: :destroy
  has_many :categories, through: :relationships

  scope :cat_id, -> (cat_id) { joins(:relationships).where("category_id = ?","#{cat_id}") }
  scope :user_id, -> (user_id) { where user_id: user_id }
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :post
  belongs_to :category

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :posts, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :find_category, only: [:edit, :update, :destroy, :show]
  before_action :authenticate_user!, except: [:index]
  before_action :admin_user, only: [:edit, :update, :destroy]

  def index
    @categories = Category.paginate(:page => params[:page], :per_page => 10)
    @categories_sort = Category.sort_by_ancestry(@categories)
    @category = Category.new
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:notice] = "Category created !"
      redirect_to categories_path
    else
      flash[:alert] = "Category creating error !"
      render :index
    end
  end

  def edit

  end

  def update
    if @category.update_attributes(category_params)
      flash[:alert] = "Category updated !"
      redirect_to categories_path
    else
      flash[:alert] = "Category updating error !"
      render :edit
    end
  end

  def show
    @posts = @category.relationships.paginate(:page => params[:page], :per_page => 10)
  end

  def destroy
    @category.destroy
    redirect_to categories_path
  end

  private

  def category_params
    params.require(:category).permit(:title, :desc, :parent_id)
  end

  def find_category
    @category = Category.find_by(id: params[:id])
  end

  def admin_user
    redirect_to(root_url) unless current_user.admin?
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :find_post, only: [:edit, :update, :show, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @categories = Category.all
    @users = User.all


    @posts = Post.where(nil)
    @posts = @posts.cat_id(params[:cat_id]) if params[:cat_id].present?
    @posts = @posts.user_id(params[:user_id]) if params[:user_id].present?
    @posts = @posts.paginate(page: params[:page], per_page: 16)
  end

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.new(post_params)
    if @post.save
      flash[:notice] = "Post created !"
      redirect_to post_path(@post)
    else
      flash[:alert] = "Post creating error !"
      render :new
    end
  end

  def edit
    @categories = Category.all
  end

  def update
    if @post.update_attributes(post_params)
      flash[:alert] = "Post updated !"
      redirect_to post_path(@post)
    else
      flash[:alert] = "Post updating error !"
      render :edit
    end
  end

  def show
    @categories = @post.relationships.all
  end

  def destroy
    @post.destroy
    redirect_to posts_path
  end

  private

  def post_params
    params.require(:post).permit(:title, :content, :desc, :thumbnail, category_ids:[])
  end

  def find_post
    @post = Post.find_by(id: params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :find_user, only: [:destroy]

  def index
    @users = User.paginate(:page => params[:page], :per_page => 10)
  end

  def update

  end

  def destroy
    @user.destroy
    redirect_to users_path
  end

  private

  def find_user
    @user = User.find_by(id: params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title = '')
    base_title = "I-web"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end

end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper

  def logged_in?
    !current_user.nil?
  end
end

app/views/categories/_category.html.erb
<tr>
    <td>
        <%= category_counter + 1 %>
    </td>
    <td class="title-table">
        <span><%= category.title %></span>
    </td>
    <td>
      <%= category.desc %>
    </td>
    <td>
    <% if logged_in? %>
      <% if current_user.admin?  %>
        <ul class="cat-action">
          <li>
            <%= link_to 'Edit', edit_category_path(category.id) %>
          </li>
          <li>
            <%= link_to 'Delete', category_path(category.id), method: :delete, data:{confirm: 'Are you sure?'} %>
          </li>
        </ul>
      <%	else %>
      <span>
        Only admin to action
      </span>
      <% end	end %>
    </td>
    <td>
        <% cat_parents = category.ancestors %>
        <% cat_parents.each do |c| %>
        <%= link_to c.title, edit_category_path(c.id), class: "href-seperator"  %>
        <% end %>
    </td>
    <td>
      <%= link_to category.relationships.count, category_path(category.id) %>
    </td>
</tr>

app/views/categories/_form.html.erb
<%= form_for(@category) do |f|  %>
  <div class="post-create-title">
    <h4>Category title</h4>
    <%= f.text_field :title, class: 'form-control', placeholder: 'Enter category title' %>
  </div>
  <div class="post-create-desc">
    <h4>Category parent</h4>
    <%= f.select(:parent_id, Category.all.collect { |p| [ p.title, p.id ] }, {:include_blank => "Select category parent"}, {:class => "form-control"} ) %>
    <%#= f.select :parent_id, Category.all.collect { |p| [ p.title, p.id ] }, {class: 'form-control', include_blank: "Select category parent",} %>
  </div>
  <div class="post-create-desc">
    <h4>Category title</h4>
    <%= f.text_area :desc, class: 'form-control', placeholder: 'Enter category description' %>
  </div>
  <div class="post-create-submit">
    <%= f.submit yield(:btn_title), class: "btn btn-submit" %>
  </div>
<%	end  %>

app/views/categories/edit.html.erb
<% provide(:title, "Update category") %>
<% provide(:btn_title, "Update category") %>
<%= render "shared/heading" %>
<div class="page-content container-fluid">
  <div class="row">
    <div class="col-md-6 offset-md-3 ">
      <%= render('categories/form') %>
    </div>
  </div>
</div>

app/views/categories/index.html.erb
<% provide(:title, "All categories") %>
<% provide(:btn_title, "Create category") %>
<%= render "shared/heading" %>
<div class="page-content container-fluid">
    <div class="page-content-item">
        <div class="row">
            <div class="col-md-4">
              <%= render('categories/form') %>
            </div>
            <div class="col-md-8">
                <table class="table cat-table">
                    <thead class="thead-dark">
                    <tr>
                        <th scope="col" class="w-5">#</th>
                        <th scope="col" class="w-20">Name</th>
                        <th scope="col" class="w-30">Description</th>
                        <th scope="col" class="w-20">Action</th>
                        <th scope="col" class="w-20">Parents</th>
                        <th scope="col" class="w-5">Count</th>
                    </tr>
                    </thead>
                    <tbody>
                        <%= render :partial => 'category', :collection => @categories_sort %>
                    </tbody>
                </table>
                <%= will_paginate @categories %>
            </div>
        </div>
    </div>
</div>

app/views/categories/show.html.erb
<% provide(:title, "Category archive") %>
<%= render "shared/heading" %>
<div class="page-content container-fluid">
  <div class="row">
    <div class="col-md-6 offset-md-3 ">
      <table class="table">
        <thead class="thead-dark">
        <tr>
          <th scope="col">#</th>
          <th scope="col">Title post</th>
          <th scope="col">Time to created</th>
        </tr>
        </thead>
        <tbody>
        <% @posts.each.with_index do |p, index| %>
          <tr>
            <td><%= index+1 %></td>
            <td><%= p.post.title %></td>
            <td><%= p.post.created_at.strftime("%Y-%m-%d") %></td>
          </tr>
        <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/layouts/_footer.html.erb
<footer class="footer"> © 2018 All rights reserved. Awesome Academy</footer>

app/views/layouts/_header.html.erb
<header class="sticky-top">
  <nav class="navbar navbar-expand-lg navbar-light">
    <div class="navbar-header">
      <%= link_to root_path do %><img src="https://getbootstrap.com/docs/4.0/assets/brand/bootstrap-solid.svg" alt=""><% end %>
    </div>

    <div class="collapse navbar-collapse">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item">
          <a class="nav-link" href="#"><i class="fas fa-search"></i></a>
        </li>
        <li class="nav-item active">
          <a class="nav-link" href="#"><i class="fas fa-bell"></i></a>
        </li>
        <li class="nav-item active">
          <a class="nav-link" href="#"><i class="fas fa-envelope"></i></a>
        </li>
        <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to current_user.email, edit_user_registration_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to destroy_user_session_path, method: :delete , class: "nav-link", title: "Log Out" do %><i class="fas fa-sign-out-alt"></i><% end %>
        </li>
        <% else %>
        <li class="nav-item">
          <%= link_to new_user_registration_path, class: "nav-link", title: "Sign Up" do %><i class="fas fa-user-plus"></i><% end %>
        </li>
        <li class="nav-item">
          <%= link_to new_user_session_path, class: "nav-link", title: "Sign In" do %><i class="fas fa-sign-in-alt"></i><% end %>
        </li>
        <% end %>
      </ul>
    </div>
  </nav>
</header>

app/views/layouts/_left-sidebar.html.erb
<div class="left-sidebar">
  <nav>
    <ul class="left-sidebar-menu">
      <li>
        <%= link_to root_path do %>
          <i class="fas fa-tachometer-alt"></i>Dashboard
        <% end %>
      </li>
      <li>
        <%= link_to posts_path do %>
          <i class="fas fa-file-alt"></i>Posts
        <% end %><i class="fas fa-angle-right click-toggle"></i>
        <ul class="sub-menu">
          <li>
            <%= link_to "All post", posts_path %>
          </li>
          <li>
            <%= link_to "Create a new post", new_post_path %>
          </li>
          <li>
            <%= link_to "Categories", categories_path %>
          </li>
          <li>
            <a href="#">Tags</a>
          </li>
        </ul>
      </li>
      <li>
        <%= link_to users_path do %><i class="fas fa-users"></i>Users</a><i class="fas fa-angle-right click-toggle"></i><% end %>
        <ul class="sub-menu">
          <li>
            <%= link_to "All Users", users_path %>
          </li>
        </ul>
      </li>
    </ul>
  </nav>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application' %>
    <%= javascript_include_tag 'application' %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" integrity="sha384-lKuwvrZot6UHsBSfcMvOkWwlCMgc0TaWr+30HWe3a4ltaBwTZhyTEggF5tJv8tbt" crossorigin="anonymous">
  </head>

  <body>
    <%= render "layouts/header"%>
    <div id="main-wrapper">
      <%= render "layouts/left-sidebar"%>
      <div class="page-wrapper">
        <%= yield %>
        <%= render "layouts/footer"%>
      </div>
    </div>
  </body>
</html>

app/views/pages/home.html.erb
<% provide(:title, "Dashboard") %>
<%= render "shared/heading" %>

app/views/posts/_filter.html.erb
<%= form_tag request.original_url, method: :get do %>
  <div class="post-filter">
    <div class="post-filter-item">
      <h3>Filter by category</h3>
      <ul class="filter-list">
        <% @categories.each do |c| %>
          <% if params[:cat_id] == c.id.to_s %>
            <li>
              <%= check_box_tag 'cat_id', c.id, true %> <span><%= c.title %></span>
            </li>
          <% else %>
            <li>
              <%= check_box_tag 'cat_id', c.id %> <span><%= c.title %></span>
            </li>
          <% end %>
        <% end %>
      </ul>
    </div>
    <div class="post-filter-item">
      <h3>Filter by user</h3>
      <ul class="filter-list">
        <% @users.each do |u| %>
          <% if params[:user_id] == u.id.to_s %>
            <li>
              <%= check_box_tag 'user_id', u.id, true %> <span><%= u.email %></span>
            </li>
          <% else %>
            <li>
              <%= check_box_tag 'user_id', u.id %> <span><%= u.email %></span>
            </li>
          <% end %>
        <% end %>
      </ul>
    </div>
    <%= submit_tag "Filter", class: 'btn btn-submit' %>
  </div>
<% end %>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="page-content-item">
    <div class="row">
      <div class="col-md-9">
        <div class="post-create-title">
          <h4>Post title</h4>
          <%= f.text_field :title, class: 'form-control', placeholder: 'Enter post title' %>
        </div>
        <div class="post-create-content">
          <h4>Post content</h4>
          <%= f.cktext_area :content, class: 'form-control' %>
        </div>
        <div class="post-create-desc">
          <h4>Post description</h4>
          <%= f.text_area :desc, class: 'form-control', placeholder: 'Enter post description' %>
        </div>
      </div>
      <div class="col-md-3">
        <div class="post-create-thumbnail">
          <h4>Categories</h4>
          <span>Select category(s)</span>
          <ul class="select-cat-wrapper">
            <%= f.collection_check_boxes :category_ids, Category.all, :id, :title do |cat| %>
              <li>
                <%= cat.check_box %>
                <%= cat.label %>
              </li>
            <% end %>
          </ul>
        </div>
        <div class="post-create-thumbnail">
          <h4>Post thumbnail</h4>
          <span>Please upload your post thumbnail</span>
          <%= f.file_field :thumbnail %>
        </div>
        <div class="post-create-submit">
          <%= f.submit yield(:btn_title), class: "btn btn-submit" %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div class="col-md-4">
  <div class="page-content-item">
    <% if post.thumbnail? %>
    <div class="post-thumb">
        <%= link_to post_path(post.id) do %>
        <%= image_tag post.thumbnail.url, class: "rounded mx-auto d-block" %>
        <% end %>
    </div>
    <% end %>
    <ul class="post-meta">
      <li>
        <span><i class="far fa-user"></i><%= post.user.email %></span>
      </li>
      <li>
        <span><i class="far fa-calendar-alt"></i><%= post.created_at.strftime("%Y-%m-%d") %></span>
      </li>
    </ul>
    <h4 class="post-title"><%= link_to post.title, post_path(post.id) %></h4>
    <div class="post-desc">
      <%= post.desc %>
    </div>
    <%= link_to 'Read more', post_path(post.id), class: "read-more" %> 
    <% if user_signed_in? %>
      <% if current_user == post.user || current_user.admin? %>/
      <%= link_to 'Edit', edit_post_path(post.id), class: "read-more" %> /
      <%= link_to 'Delete', post_path(post.id), method: :delete, data:{confirm: 'Are you sure?'}, class: "read-more" %>
      <% end %>
    <% end %>
  </div>
</div>

app/views/posts/edit.html.erb
<% provide(:title, "Edit post") %>
<% provide(:btn_title, "Update post") %>
<div class="row page-title">
  <div class="col-md-5 align-self-center">
    <h3>Edit post</h3>
  </div>
  <div class="col-md-7 align-self-center">
    <nav aria-label="breadcrumb">
      <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="#">Home</a></li>
        <li class="breadcrumb-item"><a href="#">Library</a></li>
        <li class="breadcrumb-item active" aria-current="page">Data</li>
      </ol>
    </nav>
  </div>
</div>
<div class="page-content container-fluid">
  <%= render "posts/form"	%>
</div>

app/views/posts/index.html.erb
<% provide(:title, "All posts") %>
<%= render "shared/heading" %>
<div class="page-content container-fluid">
  <div class="row">
    <div class="col-md-9">
      <div class="post-archive">
        <div class="row">
          <%= render @posts %>
        </div>
      </div>
    </div>
    <div class="col-md-3">
      <%= render('posts/filter') %>
    </div>
  </div>
  <%= will_paginate @posts %>

</div>

app/views/posts/new.html.erb
<% provide(:title, "New post") %>
<% provide(:btn_title, "Add post") %>
<%= render "shared/heading" %>
<div class="page-content container-fluid">
  <%= render "posts/form"	 %>
</div>

app/views/posts/show.html.erb
<% provide(:title, @post.title) %>
<%= render "shared/heading" %>
<div class="page-content container-fluid">
  <div class="page-content-inner">
    <h1 class="post-title"><%= @post.title %></h1>
    <ul class="post-meta">
      <li>
        <span><i class="far fa-user"></i><%= @post.user.email %></span>
      </li>
      <li>
        <span><i class="far fa-calendar-alt"></i><%= @post.created_at.strftime("%Y-%m-%d") %></span>
      </li>
      <li>
        <span><i class="far fa-folder-open"></i>
          <% @categories.each do |cat|  %>
          <%=	cat.category.title  %>,
          <% end %>
        </span>
      </li>
    </ul>
    <h2 class="sapo"><%=	@post.desc %></h2>
    <p><%= raw(@post.content) %></p>
  </div>
</div>

app/views/shared/_breadcrumb.html.erb
<div class="col-md-7 align-self-center">
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="#">Home</a></li>
      <li class="breadcrumb-item"><a href="#">Library</a></li>
      <li class="breadcrumb-item active" aria-current="page">Data</li>
    </ol>
  </nav>
</div>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_heading.html.erb
<div class="row page-title">
  <div class="col-md-5 align-self-center">
    <h3><%= yield(:title) %></h3>
  </div>
  <%= render('shared/breadcrumb') %>
</div>
<div class="alert-msg">
    <% if notice %><div class="alert alert-info"><%= notice %></div><% end %>
    <% if alert %><div class="alert alert-warning"><%= alert %></div><% end %>
</div>

app/views/users/index.html.erb
<% provide(:title, "All users") %>
<%= render "shared/heading" %>
<div class="page-content container-fluid">
  <div class="row">
    <div class="col-md-6 offset-md-3 ">
      <table class="table">
        <thead class="thead-dark">
          <tr>
            <th scope="col">#</th>
            <th scope="col">Email</th>
            <th scope="col">Time to created</th>
            <th scope="col">Action</th>
          </tr>
        </thead>
        <tbody>
          <% @users.each.with_index do |user, index| %>
          <tr>
            <td><%= index+1 %></td>
            <td><%= user.email %></td>
            <td><%= user.created_at.strftime("%Y-%m-%d") %></td>
            <td>
              <% if logged_in? %>
              <% if current_user.admin?  %>
                <ul class="cat-action">
                  <li>
                    <%= link_to 'Delete', user_path(user.id), method: :delete, data:{confirm: 'Are you sure?'} %>
                  </li>
                </ul>
              <%	else %>
              <span>
                Only admin to action
              </span>
              <% end	end %>
            </td>
          </tr>
          <%; end %>
        </tbody>
      </table>
    </div>
  </div>
</div>